import {
  Home, FileText, BookOpen, Compass, Workflow, Sparkles, SpellCheck, Search, CircleHelp, Bell,
  ChevronRight, ChevronDown, ChevronLeft, ArrowRight, ArrowLeft, Plus, Download, FileSpreadsheet,
  List, LayoutGrid, ShieldHalf, Target, Group, Users, ListOrdered, ArrowLeftRight, Link2, History,
  LogIn, LogOut, Circle, MessagesSquare, ListChecks, Clipboard, ClipboardList, Copy, Check, Clock,
  Lightbulb, Inbox, Scale, Info, CirclePlus, X, TriangleAlert, Heart, Handshake, Rocket, Zap,
  DraftingCompass, UserRound, SearchCheck, TrendingUp, Settings, Megaphone, Network, Route,
  HeartHandshake, Flag, Table, Wrench, Layers, Ban, PackageOpen, HardHat, Monitor, Contact,
  UserCheck, UserCog, KeyRound, DoorOpen, ArrowRightLeft, Gauge, Menu, type LucideIcon,
} from 'lucide-react'

const MAP: Record<string, LucideIcon> = {
  house: Home,
  'file-lines': FileText,
  book: BookOpen,
  compass: Compass,
  'diagram-project': Workflow,
  'wand-magic-sparkles': Sparkles,
  'spell-check': SpellCheck,
  'magnifying-glass': Search,
  'circle-question': CircleHelp,
  bell: Bell,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  plus: Plus,
  download: Download,
  'file-excel': FileSpreadsheet,
  'file-word': FileText,
  list: List,
  grip: LayoutGrid,
  'shield-halved': ShieldHalf,
  bullseye: Target,
  'object-group': Group,
  'users-gear': Users,
  'list-ol': ListOrdered,
  'right-left': ArrowLeftRight,
  link: Link2,
  'clock-rotate-left': History,
  'arrow-right-to-bracket': LogIn,
  'arrow-right-from-bracket': LogOut,
  circle: Circle,
  comments: MessagesSquare,
  'list-check': ListChecks,
  clipboard: Clipboard,
  'clipboard-list': ClipboardList,
  'clipboard-question': ClipboardList,
  copy: Copy,
  check: Check,
  clock: Clock,
  lightbulb: Lightbulb,
  inbox: Inbox,
  'scale-balanced': Scale,
  'circle-info': Info,
  'circle-plus': CirclePlus,
  xmark: X,
  'triangle-exclamation': TriangleAlert,
  'people-group': Users,
  heart: Heart,
  handshake: Handshake,
  rocket: Rocket,
  bolt: Zap,
  'compass-drafting': DraftingCompass,
  'user-tie': UserRound,
  'magnifying-glass-chart': SearchCheck,
  'chart-line': TrendingUp,
  gears: Settings,
  bullhorn: Megaphone,
  sitemap: Network,
  route: Route,
  'book-open': BookOpen,
  'hands-helping': HeartHandshake,
  'flag-checkered': Flag,
  'table-list': Table,
  toolbox: Wrench,
  'layer-group': Layers,
  ban: Ban,
  'box-open': PackageOpen,
  'helmet-safety': HardHat,
  desktop: Monitor,
  'address-book': Contact,
  'user-group': Users,
  'user-shield': UserCheck,
  'user-gear': UserCog,
  key: KeyRound,
  'door-open': DoorOpen,
  'arrow-right-arrow-left': ArrowRightLeft,
  'gauge-high': Gauge,
  menu: Menu,
}

export function Icon({
  name,
  className,
  size = 16,
  strokeWidth = 2,
}: {
  name?: string | null
  className?: string
  size?: number
  strokeWidth?: number
}) {
  const key = (name ?? '').replace(/^fa-/, '')
  const Cmp = MAP[key] ?? Circle
  return <Cmp className={className} size={size} strokeWidth={strokeWidth} aria-hidden="true" />
}
